[workspace]
# RustSBI library and all supported platforms
members = [
    "rustsbi",
    "k210"
]

# these profiles are required for test kernel, not RustSBI library itself
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
